name: Xavior Spade
favicon: null
layout_spectrum: 0.49656
typography_spectrum: 0
title: Xavior Spade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaebe6'
    - '#020102'
    - '#341f27'
    - '#a29494'
    - '#705d5d'
  brandStrength: 0.035233189119026065
  lightness: 0.47857186617329717
  saturation: 0.47175842453725636
  rhythmicContrast: 0.892006087815389
purpose: []
